
CREATE
  TABLE CONTROL_PP_LOG
  (
    ID              INTEGER  NOT NULL ,
    STATE           VARCHAR (50),
    WORKFLOW_LOG_ID INTEGER  NOT NULL
  ) ;

CREATE
  TABLE CONTROL_WORKFLOW
  (
    ID     INTEGER  NOT NULL ,
    REGION VARCHAR (6),
    LBD    VARCHAR (8)
  ) ;


CREATE
  TABLE CONTROL_WORKFLOW_LOG
  (
    ID          INTEGER NOT NULL ,
    WORKFLOW_ID INTEGER NOT NULL ,
    STATE       VARCHAR (50) NOT NULL
  ) ;



